version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.1
    ports:
     - 9200:9200
     - 9300:9300
    networks:
     - elastic
    volumes:
     - /Users/tdi/workspaces/elasticksearch/data:/usr/share/elasticsearch/data
    environment:
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - TZ=Asia/Seoul
     - ELASTIC_PASSWORD=zktm500cc
     - xpack.security.enabled=false
    user: root
    restart: always
    privileged: true

  kibana:
    container_name: kibana
    image: kibana:7.17.1
    ports:
     - 5601:5601
    networks:
     - elastic
    environment:
     - TZ=Asia/Seoul
     - KIBANA_SYSTEM_PASSWORD=zktm500cc
    restart: always
    privileged: true
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge